// packages/docs/react-docs/src/routes/components+/tag+/demos/tag-variants-demo.tsx
import type {ReactElement} from "react"

import {Link} from "react-router"

import {Tag} from "@qualcomm-ui/react/tag"

export function TagVariantsDemo(): ReactElement {
  return (
    <div className="flex flex-col items-start gap-2">
      {/* preview */}
      <Tag>read-only</Tag>
      <Tag variant="dismissable">dismissable</Tag>
      <Tag variant="selectable">selectable</Tag>
      <Tag render={<Link to="/components/tag" />}>link</Tag>
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/tag+/demos/tag-variants-demo.ts
import {Component} from "@angular/core"
import {RouterLink} from "@angular/router"

import {TagDirective} from "@qualcomm-ui/angular/tag"

@Component({
  imports: [RouterLink, TagDirective],
  selector: "tag-variants-demo",

  template: `
    <div class="flex flex-col items-start gap-2">
      <!-- preview -->
      <span q-tag>read-only</span>
      <span q-tag variant="dismissable">dismissable</span>
      <button q-tag variant="selectable">selectable</button>
      <a q-tag routerLink="/components/tag">link</a>
      <!-- preview -->
    </div>
  `,
})
export class TagVariantsDemo {}
