// packages/frameworks/react/src/dialog/dialog-close-button.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement} from "react"

import {type LucideIcon, X} from "lucide-react"

import {CoreDialog} from "@qualcomm-ui/react-core/dialog"
import type {ElementRenderProp, IdProp} from "@qualcomm-ui/react-core/system"
import {InlineIconButton} from "@qualcomm-ui/react/inline-icon-button"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {useQdsDialogContext} from "./qds-dialog-context"

export interface DialogCloseButtonProps
  extends IdProp, ElementRenderProp<"button"> {
  /**
   * @default X
   */
  icon?: LucideIcon
}

/**
 * A button that closes the dialog. Renders a `<button>` element by default.
 */
export function DialogCloseButton({
  icon,
  ...props
}: DialogCloseButtonProps): ReactElement {
  const qdsContext = useQdsDialogContext()
  const mergedProps = mergeProps(qdsContext.getCloseButtonBindings(), props)

  return (
    <CoreDialog.CloseTrigger>
      <InlineIconButton icon={icon || X} {...mergedProps} />
    </CoreDialog.CloseTrigger>
  )
}

// packages/frameworks/angular/src/dialog/dialog-close-button.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, computed} from "@angular/core"
import {X} from "lucide-angular"

import {CoreDialogCloseTriggerDirective} from "@qualcomm-ui/angular-core/dialog"
import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {useInlineIconButtonApi} from "@qualcomm-ui/angular/inline-icon-button"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {useQdsDialogContext} from "./qds-dialog-context.service"

/**
 * A button that closes the dialog.
 */
@Component({
  providers: [provideIcons({X})],
  selector: "[q-dialog-close-button]",
  standalone: false,
  template: `<svg qIcon="X" [q-bind]="buttonApi().getIconBindings()"></svg>`,
})
export class DialogCloseButtonComponent extends CoreDialogCloseTriggerDirective {
  protected readonly qdsContext = useQdsDialogContext()
  protected readonly buttonApi = useInlineIconButtonApi({
    emphasis: "neutral",
    size: "md",
    variant: "fixed",
  })

  constructor() {
    super()
    this.trackBindings.extendWith(
      computed(() =>
        mergeProps(
          this.buttonApi().getRootBindings(),
          this.qdsContext().getCloseButtonBindings(),
        ),
      ),
    )
  }
}
